
name: Trivy test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/somesha/trivy-demo:${{ github.sha }} .

#      - name: Install Trivy
#        run: |
#          sudo apt-get install wget apt-transport-https gnupg lsb-release
#          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
#          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
#          sudo apt-get update
#          sudo apt-get install trivy
#
#      - name: Scan image with Trivy
#        run: |
#          trivy image test/trivy:1.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/somesha/trivy-demo:${{ github.sha }}'
          format: 'table'
          output: 'trivy-results.sarif'
          exit-code: 1

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'